disabled_rules:
  - line_length
  - force_cast
  - force_try
  - operator_whitespace
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
force_try:
  severity: warning
identifier_name:
  min_length: 1
large_tuple:
  warning: 3
  error: 4
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5
